In [14]:
import tensorflow as tf
print("TensorFlow version: ",tf.__version__)

TensorFlow version:  2.18.0


In [15]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [16]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [17]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.06465597,  0.05736059, -0.14096895, -0.31984687,  0.11970115,
        -0.2007693 , -0.23926452,  0.04656538, -0.07026572, -0.4546646 ]],
      dtype=float32)

In [19]:
tf.nn.softmax(predictions).numpy()

array([[0.11764944, 0.11679427, 0.09578294, 0.08009446, 0.12430704,
        0.09022298, 0.08681583, 0.11554023, 0.10280024, 0.06999255]],
      dtype=float32)

In [20]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [21]:
loss_fn(y_train[:1], predictions).numpy()

2.4054713

In [22]:
model.compile(optimizer='adam',
                loss=loss_fn,
                metrics=['accuracy'])

In [23]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.8626 - loss: 0.4758
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9541 - loss: 0.1555
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9660 - loss: 0.1130
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9731 - loss: 0.0872
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9762 - loss: 0.0752


In [24]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 5ms/step - accuracy: 0.9765 - loss: 0.0724


[0.07238525152206421, 0.9764999747276306]

In [25]:
propability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [26]:
propability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.13583165e-08, 4.61798095e-07, 5.74653222e-06, 8.80305088e-05,
        1.23200408e-10, 9.33364532e-08, 6.38993388e-14, 9.99899387e-01,
        3.68689854e-07, 5.72268800e-06],
       [3.98404012e-08, 2.04697426e-04, 9.99716818e-01, 7.06844876e-05,
        4.18163056e-15, 1.75447542e-06, 2.54561101e-08, 5.83481898e-14,
        6.08084201e-06, 2.96750932e-13],
       [1.49028688e-06, 9.98041272e-01, 1.26695581e-04, 5.45336479e-06,
        1.63549324e-04, 2.60768479e-06, 2.70227574e-05, 1.20057235e-03,
        4.30371583e-04, 9.24140807e-07],
       [9.99686480e-01, 6.16518558e-10, 1.70327170e-04, 5.21527454e-07,
        1.89160460e-06, 1.41392329e-05, 1.01558689e-04, 1.14452023e-05,
        2.19473790e-07, 1.34497795e-05],
       [1.57413488e-05, 1.65927228e-09, 1.57793911e-05, 2.86397864e-07,
        9.75499868e-01, 6.84388624e-06, 1.17858654e-04, 1.18885255e-04,
        9.11567895e-06, 2.42156927e-02]], dtype=float32)>